apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bbe-msa-bs-order-v1
  namespace: bancaempresas
spec:
  chart:
    spec:
      releaseName: bbe-msa-bs-order-v1
      targetNamespace: bancaempresas
      chart: crd-microservice
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: bp-helm-repo
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: values-bbe-msa-bs-order-v1
    valuesKey: values.yml