# service to expose nginx deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  namespace: bancaempresas
spec:
  selector:
    app: nginx-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80